name: "Deployment"

on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published

permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    if: github.event_name != 'release'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      SERVER_ENV: staging
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      # `pnpm build` is not required because it runs on `prepare` process

      - name: "[preview] deploy Cloudflare Worker"
        id: preview
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          command: versions upload --message "Branch - ${{ github.ref_name }}"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

      - name: "[preview] Add comment for deployment URL"
        run: "gh pr comment ${{ github.event.number }} --edit-last --create-if-none --body 'Deployed to preview:\n${{ steps.preview.outputs.pages-deployment-alias-url && steps.preview.outputs.pages-deployment-alias-url || steps.preview.outputs.deployment-url }}'"
        env:
          GH_TOKEN: ${{ github.token }}

  production:
    if: github.event_name == 'release'
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      SERVER_ENV: production
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      # `pnpm build` is not required because it runs on `prepare` process

      - name: "[production] deploy Cloudflare Worker"
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
